[project]
name = "clearml-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
]

[dependency-groups]
client = [
    "clearml>=2.1.3",
]
